import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  preflight: true,
  include: ["./app/**/*.{js,jsx,ts,tsx}"],
  exclude: [],
  outdir: "styled-system",
  jsxFramework: "react",
  theme: {
    extend: {
      tokens: {
        colors: {
          primary: {
            50: { value: "#fff7ed" },
            100: { value: "#ffedd5" },
            200: { value: "#fed7aa" },
            300: { value: "#fdba74" },
            400: { value: "#fb923c" },
            500: { value: "#f97316" },
            600: { value: "#ea580c" },
            700: { value: "#c2410c" },
            800: { value: "#9a3412" },
            900: { value: "#7c2d12" },
          },
          secondary: {
            50: { value: "#f0f9ff" },
            100: { value: "#e0f2fe" },
            200: { value: "#bae6fd" },
            300: { value: "#7dd3fc" },
            400: { value: "#38bdf8" },
            500: { value: "#0ea5e9" },
            600: { value: "#0284c7" },
            700: { value: "#0369a1" },
            800: { value: "#075985" },
            900: { value: "#0c4a6e" },
          },
          success: { value: "#22c55e" },
          warning: { value: "#eab308" },
          error: { value: "#ef4444" },
          info: { value: "#3b82f6" },
          gray: {
            50: { value: "#f9fafb" },
            100: { value: "#f3f4f6" },
            200: { value: "#e5e7eb" },
            300: { value: "#d1d5db" },
            400: { value: "#9ca3af" },
            500: { value: "#6b7280" },
            600: { value: "#4b5563" },
            700: { value: "#374151" },
            800: { value: "#1f2937" },
            900: { value: "#111827" },
          },
        },
        fonts: {
          sans: { value: "'Nunito', 'Comic Neue', sans-serif" },
          display: { value: "'Fredoka', 'Nunito', sans-serif" },
          mono: { value: "'Fira Code', monospace" },
        },
        fontSizes: {
          xs: { value: "0.75rem" },
          sm: { value: "0.875rem" },
          md: { value: "1rem" },
          lg: { value: "1.125rem" },
          xl: { value: "1.25rem" },
          "2xl": { value: "1.5rem" },
          "3xl": { value: "1.875rem" },
          "4xl": { value: "2.25rem" },
          "5xl": { value: "3rem" },
          "6xl": { value: "3.75rem" },
        },
        fontWeights: {
          normal: { value: "400" },
          medium: { value: "500" },
          semibold: { value: "600" },
          bold: { value: "700" },
          extrabold: { value: "800" },
        },
        radii: {
          sm: { value: "0.25rem" },
          md: { value: "0.5rem" },
          lg: { value: "1rem" },
          xl: { value: "1.5rem" },
          "2xl": { value: "2rem" },
          full: { value: "9999px" },
        },
        shadows: {
          sm: { value: "0 1px 2px 0 rgb(0 0 0 / 0.05)" },
          md: { value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)" },
          lg: { value: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)" },
          xl: { value: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)" },
          color: { value: "0 8px 24px -4px rgb(249 115 22 / 0.3)" },
        },
      },
      semanticTokens: {
        colors: {
          background: {
            DEFAULT: { value: "{colors.gray.50}" },
            card: { value: "{colors.gray.100}" },
            primary: { value: "{colors.primary.500}" },
          },
          foreground: {
            DEFAULT: { value: "{colors.gray.900}" },
            muted: { value: "{colors.gray.600}" },
            primary: { value: "#ffffff" },
          },
          border: {
            DEFAULT: { value: "{colors.gray.200}" },
            focus: { value: "{colors.primary.400}" },
          },
        },
      },
    },
  },
});
